# Generated by Django 4.0.6 on 2023-04-29 13:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0005_alter_locacao_data_devolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='data_devolucao',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 13, 13, 55, 31, 366932, tzinfo=utc), null=True),
        ),
    ]
